### ISSUE TITLE
build-installer missing from Makefile

### ISSUE THREAD

**Issue by RichAyotte** [trilitech/jstz#324]
In the documentation, we have:
```
# Start the sandbox
make build-installer
```
However, `build-installer` is missing from the Makefile.
```sh
$ make build-installer
make: *** No rule to make target 'build-installer'.  Stop.
```

**Comment by johnyob** [comment]
Hey 👋 

Thank you for the interest in jstz 🙏 🙌 Unfortunately since the project is still in it's early phases, some of our documentation has bit-rotted 😬 

Getting started is now a bit more involved, however, we aim to improve this in the next couple of weeks :)

**Comment by RichAyotte** [comment]
Instructions in https://github.com/trilitech/jstz/pull/350 work so closing this issue.
